name: is219-ugc-tests

services:
  tests:
    build:
      context: .
      target: tests
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - test-gradle-cache:/root/.gradle
volumes:
  test-gradle-cache:
