spring:
  application:
    name: is219-ugc
  ai:
    model:
      chat: none
      embedding: none
    ollama:
      init:
        pull-model-strategy: never
server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
